export const homeLarry = {
  // id: "larry",
  to: "larryPage",
  lightBg: true,
  lightText: true,
  darkText: true,
  topLine: "Final School Project / Website",
  headline: "Linton Wellness :",
  headline2: "Living Your Most Authentic Life Possible",
  description:
    "Larry asked to design and build an affordable website that will rank well in search engines and that can scale with the business as I grow.",
  buttonLabel: "View Case Study",
  textR: "June – September 2020",
  textR2: "DESIGN LEAD",
  textR3: "User Interview",
  textR4: "Presentation",
  textR5: "Design Concept",
  textR6: "Wireframe",
  textR7: "Mock-Up",
  textR8: "Prototyping",
  textR9: "Motion Prototyping",
  dark: false,
  btnColor: false,
  primary: false,
};

export const homeVector = {
  // id: "vector",
  to: "vectorPage",
  lightBg: true,
  lightText: true,
  darkText: true,
  topLine: "Individual client project / Website , Brochure",
  headline:
    "Providing corporate site and Brochure for Vector International Academy",
  description:
    "Vector International Academy stepped school through the creation of a new innovated website and brochure that to clear intention what they provide.",
  buttonLabel: "View Case Study",
  textR: "October 2019 – February 2021",
  textR2: "DESIGN LEAD",
  textR3: "User Interview",
  textR4: "Presentation",
  textR5: "Design Concept",
  textR6: "Graphic Design",
  textR7: "Wireframe",
  textR8: "Mock-Up",
  textR9: "Prototyping",
  textR10: "Motion Prototyping",
  dark: false,
  btnColor: false,
  primary: false,
};

export const homeUI = {
  // id: "vdsilyUi",
  lightBg: true,
  lightText: true,
  darkText: true,
  topLine: "UI UX",
  headline: "Project of disciplining my creativity",
  description:
    "description description description description description description description description description description description description",
  buttonLabel: "View Case Study",
  textR: "April – July 2020",
  textR2: "UI UX design",
  textR3: "Design concept",
  textR4: "Prototyping",
  dark: false,
  btnColor: false,
  primary: true,
};

export const homeDaruma = {
  // id: "daruma",
  to: "darumaPage",
  lightBg: true,
  lightText: false,
  darkText: true,
  topLine: "top line",
  headline: "head line head line head line",
  description:
    "description description description description description description description description description description description description",
  buttonLabel: "View Case Study",
  dark: false,
  btnColor: false,
  primary: false,
};
