export const case1 = {
  name: "case1",
  to: "case1Page",
  title: "Cultivating Core User Empathy",
  tag: "Case Study 1",
  body: "Analyzing the factors that enhance user experience is a significant process before driving the car.",
  imageActivate1: true,
  imageActivate2: false,
  imageActivate3: false,
  imageActivate4: false,
  img: require("../../images/case_1_v2.png"),
  alt: "Image",
  imageLeft: true,
  paddingStart: false,
  paddingEnd: false,
  buttonLabel: "View Case Study 1",
};

export const case2 = {
  name: "case2",
  to: "case2Page",
  title: "Resolving Design Challenges",
  tag: "Case Study 2",
  body: "Challenges are ever-present, and addressing issues comprehensively is a problem-solving.",
  imageActivate1: false,
  imageActivate2: true,
  imageActivate3: false,
  imageActivate4: false,
  img: require("../../images/case_2.png"),
  alt: "Image",
  imageLeft: false,
  paddingStart: true,
  paddingEnd: false,
  buttonLabel: "View Case Study 2",
};

export const case3 = {
  name: "case3",
  to: "case3Page",
  title: "Enhancing Website Profitability",
  tag: "Case Study 3",
  body: "Product appeal and profitability improve through continuous enhancements and ongoing analysis.",
  imageActivate1: false,
  imageActivate2: false,
  imageActivate3: true,
  imageActivate4: false,
  img: require("../../images/case_3.png"),
  alt: "Image",
  imageLeft: true,
  paddingStart: true,
  paddingEnd: false,
  buttonLabel: "View Case Study 3",
};

export const case4 = {
  name: "case4",
  to: "case4Page",
  title: "Midnight Paloma",
  tag: "Case Study 4",
  body: "Midnight Paloma website was a long overdue revamp but has committed to completing it within a tight timeframe.",
  imageActivate1: false,
  imageActivate2: false,
  imageActivate3: false,
  imageActivate4: true,
  img: require("../../images/case_mp.png"),
  alt: "Image",
  imageLeft: false,
  paddingStart: true,
  paddingEnd: true,
  buttonLabel: "View Case Study 4",
};
