export const case1 = {
  name: "case1",
  to: "case1Page",
  title: "Cultivating Core User Empathy",
  body: "Analyzing the factors that enhance user experience is a significant process before driving the car.",
  imageActivate1: true,
  imageActivate2: false,
  imageActivate3: false,
  imageActivate4: false,
  img: require("../../images/case_1_v2.png"),
  alt: "Image",
  imageLeft: true,
  paddingStart: false,
  paddingEnd: false,
  buttonLabel: "View Study",
};

export const case2 = {
  name: "case2",
  to: "case2Page",
  title: "Resolving Design Challenges",
  body: "Challenges are ever-present, and addressing issues comprehensively is a problem-solving.",
  imageActivate1: false,
  imageActivate2: true,
  imageActivate3: false,
  imageActivate4: false,
  img: require("../../images/case_2.png"),
  alt: "Image",
  imageLeft: false,
  paddingStart: true,
  paddingEnd: false,
  buttonLabel: "View Study",
};

export const case3 = {
  name: "case3",
  to: "case3Page",
  title: "Enhancing Website Profitability",
  body: "Product appeal and profitability improve through continuous enhancements and ongoing analysis.",
  imageActivate1: false,
  imageActivate2: false,
  imageActivate3: true,
  imageActivate4: false,
  img: require("../../images/case_3.png"),
  alt: "Image",
  imageLeft: true,
  paddingStart: true,
  paddingEnd: false,
  buttonLabel: "View Study",
};

export const caseMp = {
  name: "mp",
  to: "caseMpPage",
  title: "Mnamenight Paloma",
  body: "Mnamenight Paloma website was a long overdue revamp but has committed to completing it within a tight timeframe.",
  imageActivate1: false,
  imageActivate2: false,
  imageActivate3: false,
  imageActivate4: true,
  img: require("../../images/case_mp.png"),
  alt: "Image",
  imageLeft: false,
  paddingStart: true,
  paddingEnd: true,
  buttonLabel: "View Study",
};
