export const homeLarry = {
  // id: "larry",
  to: "larryPage",
  lightBg: true,
  lightText: true,
  darkText: true,
  topLine: "Final School Project / Website",
  headline: "Linton Wellness :",
  headline2: "Living Your Most Authentic Life Possible",
  description:
    "Larry asked to design and build an affordable website that will rank well in search engines and that can scale with the business as it grows.",
  buttonLabel: "View Case Study",
  textR: "June – September 2020",
  textR2: "DESIGN LEAD",
  textR3: "User Interview",
  textR4: "Presentation",
  textR5: "Design Concept",
  textR6: "Wireframe",
  textR7: "Mock-Up",
  textR8: "Prototyping",
  textR9: "Motion Prototyping",
  dark: false,
  btnColor: false,
  primary: false,
  primarySns: true,
};

export const homeVector = {
  // id: "vector",
  to: "vectorPage",
  lightBg: true,
  lightText: true,
  darkText: true,
  topLine: "Self-employed project / Website , Brochure",
  headline:
    "Providing corporate site and Brochure for Vector International Academy",
  description:
    "I was hired by Vector Internationa Academy to recreate and modernize their websites. I have applied design innovation to their website and brochure.",
  buttonLabel: "View Case Study",
  textR: "October 2019 – February 2021",
  textR2: "DESIGN LEAD",
  textR3: "User Interview",
  textR4: "Presentation",
  textR5: "Design Concept",
  textR6: "Graphic Design",
  textR7: "Wireframe",
  textR8: "Mock-Up",
  textR9: "Prototyping",
  textR10: "Motion Prototyping",
  dark: false,
  btnColor: false,
  primary: false,
  primarySns: true,
};

export const homeUI = {
  // id: "dailyUi",
  lightBg: true,
  lightText: true,
  darkText: true,
  topLine: "UI UX",
  headline: "100-day design challenge : Self-commitment to design every day",
  description:
    "I tried to hone my design skills by adhering to a daily self-challenge to design and create.",
  buttonLabel: "View Case Study",
  textR: "April – July 2020",
  textR2: "UI UX design",
  textR3: "Design concept",
  textR4: "Prototyping",
  dark: false,
  btnColor: false,
  primary: true,
  primarySns: false,
};

export const homeDaruma = {
  // id: "daruma",
  to: "darumaPage",
  lightBg: true,
  lightText: true,
  darkText: true,
  topLine: "Self-employed project / Website , Web Development ",
  headline: "The offer to create a refined website for a BBQ restaurant",
  description:
    "Founded five decades ago, Daruma is a famous BBQ restaurant in my city. Their website needed improvements from the concept stage to the final content management stage. I delivered best results in the shortest amount of time and my clients were extremely satisfied.",
  buttonLabel: "View Case Study",
  textR: "November 2020 – January 2021",
  textR2: "WEB DEVELOPMENT",
  textR3: "Direction and Management",
  textR4: "Arrange Photographer",
  textR5: "Overseer of all Design",
  textR6: "User Interview",
  textR7: "Prototyping",
  textR8: "HTML , CSS",
  textR9: "React.js",
  textR10: "React Bootstrap",
  textR11: "Styled components",
  textR12: "Implementation",
  dark: false,
  btnColor: false,
  primary: false,
  primarySns: true,
};
